### ISSUE TITLE
Extra information and documentation

### ISSUE THREAD

**Issue by Nomaq** [start-react/sb-admin-react#11]
Hello great theme 
i just wanted to ask a few questions 
how do i set the production or development environment before running the server how do i build a production or development environment separately thank you

**Comment by shwetapal** [comment]
Hi,thanks for appreciating.
Please follow this url for the issue:https://github.com/start-react/sb-admin-react/blob/master/README.md

**Comment by Nomaq** [comment]
Hey thank you very much for you quick response, i read the read me it helped me set my environment but i was asking more on tems of production and development builds this theme has two files 
webpack.local.config.js
webpack.production.config.js

and in the server js its searchig for process.env.PRODUCTION i was aking if to switch from the two environments there is somethis like npm build production/development or do i need to change some cofing file thank you again for your response

**Comment by shwetapal** [comment]
For development mode just use npm start, npm build only works for production. Thanks.

**Comment by sarika01** [comment]
This is a little late, but if you would like to build for development or production, the webpack config file can be specified as follows:
In the package.json, under "scripts", you can specify the config file to use for "build" command.
