### ISSUE TITLE
build generates invalid character

### ISSUE THREAD

**Issue by sergio-dias** [start-react/sb-admin-react#15]
Hi,

I'm facing a problema when using  "npm run build".

Some texts on sample applications are generated with an extra "Â" character in front of it.
![image](https://cloud.githubusercontent.com/assets/20519034/18096174/bb23c65e-6eaf-11e6-9428-f113d5a31f08.png)

This behavior doesn't happens when running application with "npm start".

I have just dowloaded sb-admin and didn't make any change. Running on mac osx 10.11.6, npm 2.15.1

Cheers

**Comment by ssteinerx** [comment]
I have a much updated fork at: [ssteinerX](https://github.com/ssteinerx/sb-admin-react)

Please check to see if I've somehow corrected the problem -- I've updated all of the build tools and React itself as well.

**Comment by sergio-dias** [comment]
Thank you ssteinerx, but it doesn't help. I will research a little bit more and try to find out what is happening.

**Comment by ssteinerx** [comment]
Check this: http://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp

> Somewhere in that mess, the non-breaking spaces from the HTML template (the  s) are encoding as ISO-8859-1 so that they show up incorrectly as an "Â" character
> That'd be encoding to UTF-8 then, not ISO-8859-1. The non-breaking space character is byte 0xA0 in ISO-8859-1; when encoded to UTF-8 it'd be 0xC2,0xA0, which, if you (incorrectly) view it as ISO-8859-1 comes out as "Â ". That includes a trailing nbsp which you might not be noticing; if that byte isn't there, then something else has mauled your document and we need to see further up to find out what.

**Comment by sergio-dias** [comment]
Thanks, ssteinerx . That's it!

**Comment by ssteinerx** [comment]
@sergio-finanzero Great!  Glad I could help.  If you want to raise further issues, please do so on my fork of this project as this repo seems to have been abandoned and my fork is so far ahead that I almost have as many commits on it as the original project did when I forked it.

**Comment by sarika01** [comment]
Thanks @ssteinerx for solving this.
