### ISSUE TITLE
Trying to deploy to AWS S3

### ISSUE THREAD

**Issue by rickybasse** [start-react/sb-admin-react#43]
Hi guys, I'm really new to React and I was playing around with this awesome template. 
I was wondering how to deploy it to AWS S3, after I run the 'npm run build' command in my /build folder there is no index.html, and also in /src folder there isn't one. I have to create a custom one by myself or I'm missing something?

/build tree:

![tree-sb](https://user-images.githubusercontent.com/19646083/33391230-ad8f7cae-d538-11e7-8a8c-494177c0462f.png)

**Comment by sarika01** [comment]
The html file is created from /src/components/Html.js

**Comment by rickybasse** [comment]
Thanks for the answer. Actually I’ve notice that Html.js is creating the html file at the start, the fact is that on S3 I need a proper *.html in order to be able to host my test app on it. Maybe I’ll try to extract the html lines and put them into a *.html file and then call the App component from it

**Comment by sarika01** [comment]
I am not sure if I got your requirement right. But, after building, if you run the server.js file though node server, you would get the generated html file at the client side.
This is different from deploying an app on the web server where the index.html static file is served.

**Comment by rickybasse** [comment]
Running server.js with node server is ok but what if I want to put this test app on AWS? Usually I put React webapps on S3 whit “static web hosting” option on, I’m wondering if it’s possible to do the same thing also in this case. With other react templates (create-react-app for example) I have no trouble doing the deploy because all them have an index.html acting as starting file. 

If I ask to S3 to start my application invoking server.js it simply show the code of this file on the browser window. I know that probably this is a noib question but I’ve searched all day for a solution and didn’t find anything.

**Comment by sarika01** [comment]
This is not going to work with 'static web hosting'. Since, this app has an iso-morphic structure, the first rendering comes from the server side. So, a node server is required to host this.
