### ISSUE TITLE
Got WARNINGS when running npm install

### ISSUE THREAD

**Issue by owieboy** [start-react/sb-admin-react#5]
I got this WARNINGS when running `npm install`

![selection_429](https://cloud.githubusercontent.com/assets/7962021/12541656/af925c44-c354-11e5-92cf-653d3567d8f7.png)

What does it mean?

**Comment by sarika01** [comment]
it's uglify letting you know that it has stripped out unreachable code.

**Comment by ssteinerx** [comment]
@sarika Please close this isssue, it's not an issue, just an uglify warning and could only be fixed by chasing down every dependency's warnings.

**Comment by sarika01** [comment]
Closing this issue as 'just warnings'.
