### ISSUE TITLE
Shrinking the window, UI is distorted.

### ISSUE THREAD

**Issue by jhunexjun** [start-react/sb-admin-react#7]
Looks like there's bug when I shrink my Google Chrome Window and IE. I compared it with the one without JS framework and it's working correctly. What it does is it doesn't toggle into collapsible button but retain it's location and therefore overlaps the header menu.
![distorted ui](https://cloud.githubusercontent.com/assets/6801369/13364031/9ec12856-dd07-11e5-80f2-4b3103bf646b.png)

Google Chrome Version 48.0.2564.116 m
IE 11.0.9600.18204

**Comment by sarika01** [comment]
This issue has been fixed.

**Comment by sarika01** [comment]
Marking this as closed.
