### ISSUE TITLE
throwing lots of error on npm start

### ISSUE THREAD

**Issue by yogeshpathade** [start-react/sb-admin-react#8]
Dear contributor, I am seeing lot of errors related incorrect filename or directory and missing things.
Could you check it. I want to use this theme for my app.

**Comment by sanketsahu** [comment]
"lot of errors". Please define that.

**Comment by yogeshpathade** [comment]
The first error after npm start
ERROR in ./src/app.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./routers/Routes in /home/<pathto webapp>/WebAppServer/sb-admin-react/src
 @ ./src/app.jsx 31:21-48

![image](https://cloud.githubusercontent.com/assets/878487/13478592/d36f45b6-e125-11e5-966e-a28f66b11dec.png)

**Comment by yogeshpathade** [comment]
Looks like the app.jsx refers to Routes.jsx but the actual file name is routes.jsx 

![image](https://cloud.githubusercontent.com/assets/878487/13478748/a37575aa-e126-11e5-8b25-eaa1f23eeb27.png)

If I correct the name in app.jsx as routes.jsx

![image](https://cloud.githubusercontent.com/assets/878487/13478787/dd96388c-e126-11e5-8197-c07310842b78.png)

and if I run the npm start again then I get big list of errors related to Module not found: Error: Cannot resolve 'file' or 'directory' in the routes.jsx

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Tables in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 29:38-85

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Forms in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 33:37-83

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/PanelsWells in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 37:43-95

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Buttons in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 41:39-87

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Notifications in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 45:45-99

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Typography in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 49:42-93

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Icons in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 53:37-83

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Grid in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 57:36-81

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/Blank in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 61:37-83

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/FlotCharts in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 65:42-93

ERROR in ./src/routers/routes.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/pages/dashboard/MorrisjsCharts in /home/WebAppServer/sb-admin-react/src/routers
 @ ./src/routers/routes.jsx 69:46-101

ERROR in ./src/components/layouts/Dashboard/index.jsx
Module not found: Error: Cannot resolve module 'jQuery' in /home/WebAppServer/sb-admin-react/src/components/layouts/Dashboard
 @ ./src/components/layouts/Dashboard/index.jsx 21:14-31

ERROR in ./src/components/common/AsyncElement.js
Module not found: Error: Cannot resolve module 'NProgress' in /home/WebAppServer/sb-admin-react/src/components/common
 @ ./src/components/common/AsyncElement.js 19:17-37

**Comment by sanketsahu** [comment]
It might be an issue with upper / lower cases. You might be on a
case-sensitive file-system.

Follow common debugging procedures like comment out things one-by-one and
see what exactly is the problem.

I believe it's a problem because of the case-sensitive file-system.

**Comment by sarika01** [comment]
changed the file-names for case-sensitive cases.

**Comment by sarika01** [comment]
Closing this as fixed for case-sensitive filenames.
